/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Record;
import Models.Student;
import java.awt.event.ActionEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.Socket;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author DTTM
 */
public class FormTest extends javax.swing.JFrame {

    Socket client;
    DataInputStream dataInputStream;
    ObjectInputStream objectInputStream;
    DataOutputStream dataOutputStream;
    int port = 1234;
    String host = "localhost";
    int score = 0;
    int number = 0;
    public int minute = 0, second = 4;
    Timer timer;

    /**
     * Creates new form TestForm
     */
    public FormTest() {
        initComponents();
        this.setLocationRelativeTo(null);
        A.setActionCommand("A");
        B.setActionCommand("B");
        C.setActionCommand("C");
        D.setActionCommand("D");
        
        lbName.setText(Main.student.getStudentName());
        lbLevel.setText(Main.test.getLevel());
        txtQ.setText("Câu hỏi: " + (number + 1));
        txtQuestion.setText(Main.test.getMultipleChoiceQuestion().get(number).getQuestion());
        txtAnswerA.setText(Main.test.getMultipleChoiceQuestion().get(number).getChoices().get("A"));
        txtAnswerB.setText(Main.test.getMultipleChoiceQuestion().get(number).getChoices().get("B"));
        txtAnswerC.setText(Main.test.getMultipleChoiceQuestion().get(number).getChoices().get("C"));
        txtAnswerD.setText(Main.test.getMultipleChoiceQuestion().get(number).getChoices().get("D"));
        numberOfQuestion.setText((number + 1) + "/" + Main.test.getMultipleChoiceQuestion().size());
//        timer = new Timer(1000, (ActionEvent e) -> {
//            if (second == 0 && minute > 0) {
//                minute--;
//                second = 60;
//            } else if (second == 0 && minute == 0) {
//                timer.stop();
//                minute = 2;
//                second = 60;
//                timer.start();
//                btnNext.doClick();
//                return;
//            }
//
//            second--;
//
//            String sec = second < 10 ? "0" + second : second + "";
//            String min = minute < 10 ? "0" + minute : minute + "";
//            lbTimer.setText(min + ":" + sec);
//        });
//        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choiceGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        numberOfQuestion = new javax.swing.JLabel();
        txtQ = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbLevel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();
        txtAnswerA = new javax.swing.JTextField();
        txtAnswerB = new javax.swing.JTextField();
        txtAnswerC = new javax.swing.JTextField();
        txtAnswerD = new javax.swing.JTextField();
        btnDone = new javax.swing.JButton();
        lbTimer = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Trình độ:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Họ và tên:");

        choiceGroup.add(A);
        A.setText("A: ");
        A.setActionCommand("A");

        choiceGroup.add(B);
        B.setText("B:");
        B.setActionCommand("B");

        choiceGroup.add(C);
        C.setText("C:");
        C.setActionCommand("C");

        choiceGroup.add(D);
        D.setText("D:");
        D.setActionCommand("D");

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        numberOfQuestion.setText("15/20");

        txtQ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtQ.setText("Câu hỏi 1:");

        lbName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbName.setText("Lưu Tiến Phát");

        lbLevel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbLevel.setText("A");

        txtQuestion.setEditable(false);
        txtQuestion.setColumns(20);
        txtQuestion.setLineWrap(true);
        txtQuestion.setRows(2);
        jScrollPane1.setViewportView(txtQuestion);

        txtAnswerA.setEditable(false);

        txtAnswerB.setEditable(false);

        txtAnswerC.setEditable(false);

        txtAnswerD.setEditable(false);

        btnDone.setText("Nộp bài");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        lbTimer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTimer.setText("05:00");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberOfQuestion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDone)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAnswerC, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAnswerD, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtQ)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAnswerB, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(46, 46, 46)
                                .addComponent(lbTimer))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnswerA, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbLevel)
                    .addComponent(lbTimer)
                    .addComponent(jButton1))
                .addGap(28, 28, 28)
                .addComponent(txtQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(txtAnswerA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAnswerB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C)
                    .addComponent(txtAnswerC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D)
                    .addComponent(txtAnswerD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfQuestion)
                    .addComponent(btnNext)
                    .addComponent(btnDone))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        String choice = choiceGroup.getSelection().getActionCommand();
        if (choice.equalsIgnoreCase(Main.test.getMultipleChoiceQuestion().get(number).getAnswer())) {
            score += 20;
        }

        choiceGroup.clearSelection();

        if (number == Main.test.getMultipleChoiceQuestion().size() - 1) {
            Main.test.setScore(score);
            writeResult();
            return;
        }

        number++;
        txtQ.setText("Câu hỏi: " + (number + 1));
        txtQuestion.setText(Main.test.getMultipleChoiceQuestion().get(number).getQuestion());
        txtAnswerA.setText(Main.test.getMultipleChoiceQuestion().get(number).getChoices().get("A"));
        txtAnswerB.setText(Main.test.getMultipleChoiceQuestion().get(number).getChoices().get("B"));
        txtAnswerC.setText(Main.test.getMultipleChoiceQuestion().get(number).getChoices().get("C"));
        txtAnswerD.setText(Main.test.getMultipleChoiceQuestion().get(number).getChoices().get("D"));
        numberOfQuestion.setText((number + 1) + "/" + Main.test.getMultipleChoiceQuestion().size());


    }//GEN-LAST:event_btnNextActionPerformed

    private void writeResult() {
        String studentId = Main.student.getStudentId();
        String datetime = Main.test.getDatetime().withNano(0).format(DateTimeFormatter.ISO_DATE_TIME);
        String scoreString = Integer.toString(Main.test.getScore());
        String level = Main.test.getLevel();

        try {
            client = new Socket(host, port);
            //dataInputStream = new DataInputStream((client.getInputStream()));
            objectInputStream = new ObjectInputStream(client.getInputStream());
            dataOutputStream = new DataOutputStream(client.getOutputStream());

            dataOutputStream.writeUTF("write");
            dataOutputStream.writeUTF(studentId);
            dataOutputStream.writeUTF(datetime);
            dataOutputStream.writeUTF(scoreString);
            dataOutputStream.writeUTF(level);

            Main.student.setRecords((ArrayList<Record>) objectInputStream.readObject());

            new FormResult().setVisible(true);
            this.dispose();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(FormTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog(null, "Bạn muốn nộp bài chứ?", "", JOptionPane.OK_CANCEL_OPTION);
        if (choose == JOptionPane.OK_OPTION) {
            Main.test.setScore(score);
            writeResult();
            return;
        }
    }//GEN-LAST:event_btnDoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormTest().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton D;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup choiceGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLevel;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbTimer;
    private javax.swing.JLabel numberOfQuestion;
    private javax.swing.JTextField txtAnswerA;
    private javax.swing.JTextField txtAnswerB;
    private javax.swing.JTextField txtAnswerC;
    private javax.swing.JTextField txtAnswerD;
    private javax.swing.JLabel txtQ;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables
}
